"""create_pagos_pago_entregas

Revision ID: 388c17d81ee0
Revises: v005
Create Date: 2026-05-17 16:49:21.491879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "388c17d81ee0"
down_revision: Union[str, None] = "v005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS tipo_cuenta")
    op.execute("DROP TYPE IF EXISTS estado_pago")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("numero_comprobante", sa.String(length=100), nullable=False),
        sa.Column("fecha_pago", sa.Date(), nullable=False),
        sa.Column("banco_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo_cuenta",
            sa.Enum(
                "corriente",
                "ahorros",
                "transferencia",
                "cheque",
                "efectivo",
                name="tipo_cuenta",
            ),
            nullable=False,
        ),
        sa.Column("nombre_titular", sa.String(length=255), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valor_aplicado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "estado", sa.Enum("activo", "eliminado", name="estado_pago"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["banco_id"],
            ["bancos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["usuarios.id"],
            name="fk_created_by_usuarios",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["usuarios.id"],
            name="fk_deleted_by_usuarios",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["usuarios.id"],
            name="fk_updated_by_usuarios",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pagos_banco_id", "pagos", ["banco_id"], unique=False)
    op.create_index("ix_pagos_estado", "pagos", ["estado"], unique=False)
    op.create_index("ix_pagos_fecha_pago", "pagos", ["fecha_pago"], unique=False)
    op.create_table(
        "pago_entregas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pago_id", sa.UUID(), nullable=False),
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("monto_aplicado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["usuarios.id"],
            name="fk_created_by_usuarios",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["usuarios.id"],
            name="fk_deleted_by_usuarios",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entregas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pago_id"],
            ["pagos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["usuarios.id"],
            name="fk_updated_by_usuarios",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pago_id", "entrega_id", name="uq_pago_entregas_pago_entrega"
        ),
    )
    op.create_index(
        "ix_pago_entregas_entrega_id", "pago_entregas", ["entrega_id"], unique=False
    )
    op.create_index(
        "ix_pago_entregas_pago_id", "pago_entregas", ["pago_id"], unique=False
    )
    op.drop_index(op.f("ix_bancos_nombre"), table_name="bancos")
    op.create_unique_constraint(None, "bancos", ["nombre"])
    op.drop_index(op.f("ix_destinatarios_identificacion"), table_name="destinatarios")
    op.create_unique_constraint(None, "destinatarios", ["identificacion"])
    op.create_foreign_key(
        "fk_created_by_usuarios",
        "entrega_items",
        "usuarios",
        ["created_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_deleted_by_usuarios",
        "entrega_items",
        "usuarios",
        ["deleted_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_updated_by_usuarios",
        "entrega_items",
        "usuarios",
        ["updated_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_created_by_usuarios",
        "entregas",
        "usuarios",
        ["created_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_deleted_by_usuarios",
        "entregas",
        "usuarios",
        ["deleted_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_updated_by_usuarios",
        "entregas",
        "usuarios",
        ["updated_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_updated_by_usuarios",
        "kardex_movimientos",
        "usuarios",
        ["updated_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_deleted_by_usuarios",
        "kardex_movimientos",
        "usuarios",
        ["deleted_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_created_by_usuarios",
        "kardex_movimientos",
        "usuarios",
        ["created_by"],
        ["id"],
        use_alter=True,
    )
    op.drop_index(op.f("ix_productos_codigo_principal"), table_name="productos")
    op.create_unique_constraint(None, "productos", ["codigo_principal"])
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.create_foreign_key(
        "fk_deleted_by_usuarios",
        "xml_item_ingresos",
        "usuarios",
        ["deleted_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_updated_by_usuarios",
        "xml_item_ingresos",
        "usuarios",
        ["updated_by"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_created_by_usuarios",
        "xml_item_ingresos",
        "usuarios",
        ["created_by"],
        ["id"],
        use_alter=True,
    )
    op.drop_index(op.f("ix_xml_items_codigo_principal"), table_name="xml_items")
    op.drop_index(op.f("ix_xml_items_xml_id_codigo"), table_name="xml_items")
    op.drop_index(op.f("ix_xmls_clave_acceso"), table_name="xmls")
    op.drop_index(op.f("ix_xmls_fecha_emision"), table_name="xmls")
    op.drop_index(op.f("ix_xmls_ruc_emisor"), table_name="xmls")
    op.create_unique_constraint(None, "xmls", ["clave_acceso"])
    # ### end Alembic commands ###

    op.create_check_constraint(
        "ck_entregas_saldo_no_negativo",
        "entregas",
        "saldo_pendiente >= 0",
    )


def downgrade() -> None:
    op.drop_constraint("ck_entregas_saldo_no_negativo", "entregas")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("xmls_clave_acceso_key", "xmls", type_="unique")
    op.create_index(op.f("ix_xmls_ruc_emisor"), "xmls", ["ruc_emisor"], unique=False)
    op.create_index(
        op.f("ix_xmls_fecha_emision"), "xmls", ["fecha_emision"], unique=False
    )
    op.create_index(op.f("ix_xmls_clave_acceso"), "xmls", ["clave_acceso"], unique=True)
    op.create_index(
        op.f("ix_xml_items_xml_id_codigo"),
        "xml_items",
        ["xml_id", "codigo_principal"],
        unique=False,
    )
    op.create_index(
        op.f("ix_xml_items_codigo_principal"),
        "xml_items",
        ["codigo_principal"],
        unique=False,
    )
    op.drop_constraint(
        "fk_created_by_usuarios", "xml_item_ingresos", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_updated_by_usuarios", "xml_item_ingresos", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_deleted_by_usuarios", "xml_item_ingresos", type_="foreignkey"
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.drop_constraint("productos_codigo_principal_key", "productos", type_="unique")
    op.create_index(
        op.f("ix_productos_codigo_principal"),
        "productos",
        ["codigo_principal"],
        unique=True,
    )
    op.drop_constraint(
        "fk_created_by_usuarios", "kardex_movimientos", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_deleted_by_usuarios", "kardex_movimientos", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_updated_by_usuarios", "kardex_movimientos", type_="foreignkey"
    )
    op.drop_constraint("fk_updated_by_usuarios", "entregas", type_="foreignkey")
    op.drop_constraint("fk_deleted_by_usuarios", "entregas", type_="foreignkey")
    op.drop_constraint("fk_created_by_usuarios", "entregas", type_="foreignkey")
    op.drop_constraint("fk_updated_by_usuarios", "entrega_items", type_="foreignkey")
    op.drop_constraint("fk_deleted_by_usuarios", "entrega_items", type_="foreignkey")
    op.drop_constraint("fk_created_by_usuarios", "entrega_items", type_="foreignkey")
    op.drop_constraint(
        "destinatarios_identificacion_key", "destinatarios", type_="unique"
    )
    op.create_index(
        op.f("ix_destinatarios_identificacion"),
        "destinatarios",
        ["identificacion"],
        unique=True,
    )
    op.drop_constraint("bancos_nombre_key", "bancos", type_="unique")
    op.create_index(op.f("ix_bancos_nombre"), "bancos", ["nombre"], unique=True)
    op.drop_index("ix_pago_entregas_pago_id", table_name="pago_entregas")
    op.drop_index("ix_pago_entregas_entrega_id", table_name="pago_entregas")
    op.drop_table("pago_entregas")
    op.drop_index("ix_pagos_fecha_pago", table_name="pagos")
    op.drop_index("ix_pagos_estado", table_name="pagos")
    op.drop_index("ix_pagos_banco_id", table_name="pagos")
    op.drop_table("pagos")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS tipo_cuenta")
    op.execute("DROP TYPE IF EXISTS estado_pago")
